/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#000000',
        foreground: '#ffffff',
        muted: {
          DEFAULT: '#1a1a1a',
          foreground: '#a0a0a0',
        },
        accent: '#333333',
        'app-border': '#222222',
        "surface-container-high": "#2a2a2a",
        "tertiary": "#fdb78e",
        "primary-fixed": "#eaddff",
        "on-surface-variant": "#cbc4d2",
        "on-primary": "#ffffff",
        "surface-container-highest": "#353534",
        "secondary": "#cec0e8",
        "on-secondary": "#352b4a",
        "outline-variant": "#494550",
        "on-background": "#e5e2e1",
        "surface-dim": "#131313",
        "error": "#ffb4ab",
        "surface-container-low": "#1c1b1b",
        "secondary-fixed-dim": "#cec0e8",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed-dim": "#fdb78e",
        "on-primary-container": "#eaddff",
        "surface-tint": "#d1bcff",
        "surface-container": "#201f1f",
        "inverse-on-surface": "#313030",
        "surface": "#131313",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#4b4162",
        "on-secondary-container": "#bcafd6",
        "primary": "#7c3aed",
        "error-container": "#93000a",
        "surface-bright": "#3a3939",
        "surface-container-lowest": "#0e0e0e",
        "on-surface": "#ffffff",
        "inverse-primary": "#6950a2",
        "on-primary-fixed-variant": "#503788",
        "on-secondary-fixed": "#1f1634",
        "on-primary-fixed": "#24005b",
        "on-tertiary-container": "#bc7e59",
        "secondary-container": "#4b4162",
        "on-tertiary-fixed-variant": "#6a3a1b",
        "on-tertiary-fixed": "#321200",
        "tertiary-container": "#411a00",
        "secondary-fixed": "#eaddff",
        "primary-fixed-dim": "#d1bcff",
        "tertiary-fixed": "#ffdbc8",
        "primary-container": "#4c1d95",
        "outline": "#948e9c",
        "surface-variant": "#353534",
        "on-tertiary": "#4f2506"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Space Grotesk", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
